// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'btnContainer': string;
  'buttons': string;
  'container': string;
}
export const cssExports: CssExports
export default cssExports
