// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'image': string;
  'itemContent': string;
  'itemName': string;
  'message': string;
}
export const cssExports: CssExports;
export default cssExports;
