// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonBlock': string;
  'buttonPriceBlock': string;
  'container': string;
  'contentBlock': string;
  'currentPriceBlock': string;
  'currentPriceBlock__price': string;
  'currentPriceBlock__title': string;
  'descriptionBlock': string;
  'descriptionBlock__title': string;
  'hide': string;
  'image': string;
  'isInStock': string;
  'photoBlock': string;
  'productTitle': string;
  'soldOut': string;
  'stringContainer': string;
  'stringContainer__content': string;
  'stringContainer__name': string;
}
export const cssExports: CssExports;
export default cssExports;
