// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'auctionHeader': string;
  'cashContainer': string;
  'container': string;
  'deleteImageButton': string;
  'emailContainer': string;
  'emailValue': string;
  'form': string;
  'input': string;
  'loadImageButton': string;
  'loadImageButtonContainer': string;
  'photoContainer': string;
  'spinner': string;
}
export const cssExports: CssExports
export default cssExports
