// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'itemCarousel3Position': string;
  'itemCarousel4Position': string;
  'itemCarousel5Position': string;
  'productNavigation': string;
}
export const cssExports: CssExports
export default cssExports
