// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'closeBtn': string;
  'container': string;
  'image': string;
}
export const cssExports: CssExports;
export default cssExports;
