export const FETCH_PRODUCT = 'PRODUCT_PAGE/FETCH_PRODUCT'
export const FETCH_CURRENT_PRICE = 'PRODUCT_PAGE/FETCH_CURRENT_PRICE'
export const DELETE_CURRENT_PRICE = 'PRODUCT_PAGE/DELETE_CURRENT_PRICE'
