// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'image': string;
  'isInStock': string;
  'item': string;
  'itemContainer': string;
  'itemContent': string;
  'link': string;
  'price': string;
  'priceData': string;
  'priceName': string;
  'productName': string;
  'soldOut': string;
  'timer': string;
}
export const cssExports: CssExports;
export default cssExports;
