// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'logo': string;
  'logoAndNavButtons': string;
  'navButtonsContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
