// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'copyright': string;
}
export const cssExports: CssExports
export default cssExports
