// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'configureIcon': string;
  'configureIconContainer': string;
  'configureList': string;
  'enterButton': string;
  'exitBlock': string;
  'exitButtonContainer': string;
  'hiddenExit': string;
  'hide': string;
  'loginBlock': string;
  'money': string;
  'moneyBlock': string;
  'userName': string;
}
export const cssExports: CssExports;
export default cssExports;
