// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'auctionHeader': string;
  'auctionParametersLine': string;
  'btn': string;
  'container': string;
  'datepicker': string;
  'fieldInput': string;
  'fieldName': string;
  'form': string;
  'generalCharacteristic': string;
  'header': string;
  'infoBlock': string;
  'loadImageContainer': string;
  'messageAddProduct': string;
  'priceParameters': string;
  'spinner': string;
  'startDateDatepicker': string;
  'stepTimeParameters': string;
}
export const cssExports: CssExports
export default cssExports
