// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'icon': string;
  'item': string;
  'link': string;
}
export const cssExports: CssExports
export default cssExports
