// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bodyContainer': string;
  'content': string;
  'header': string;
  'image': string;
}
export const cssExports: CssExports;
export default cssExports;
