// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'image': string;
  'isInStock': string;
  'item': string;
  'itemContent': string;
  'photo': string;
  'price': string;
  'priceData': string;
  'priceName': string;
  'productName': string;
  'soldOut': string;
  'timer': string;
}
export const cssExports: CssExports
export default cssExports
