// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'description': string;
  'descriptionContainer': string;
  'descriptionParagraph': string;
  'navigate': string;
  'photo': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
