// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'dateDatepicker': string;
  'datepicker': string;
  'error': string;
  'fieldName': string;
}
export const cssExports: CssExports;
export default cssExports;
