// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'cashModal': string;
  'errorMessage': string;
  'form': string;
  'hide': string;
  'input': string;
  'inputError': string;
  'title': string;
}
export const cssExports: CssExports
export default cssExports
