// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'container': string;
  'error': string;
  'fieldInput': string;
  'fieldName': string;
  'form': string;
  'userIsRegistred': string;
}
export const cssExports: CssExports;
export default cssExports;
